/* eslint-disable */
const ROCK_SETS = [
  {
    id: 'top-50-common',
    name: 'Top 50 Common Rocks',
    icon: '🌍',
    description: 'The most common rocks found around the world',
    rocks: [
      { id: 'granite',      name: 'Granite',      type: 'igneous',      rarity: 'common',    description: 'Coarse crystals of quartz and feldspar you can see with your eyes' },
      { id: 'basalt',       name: 'Basalt',       type: 'igneous',      rarity: 'common',    description: 'Dark fine-grained rock that makes up most of the ocean floor' },
      { id: 'obsidian',     name: 'Obsidian',     type: 'igneous',      rarity: 'common',    description: 'Shiny black volcanic glass with razor-sharp edges' },
      { id: 'pumice',       name: 'Pumice',       type: 'igneous',      rarity: 'common',    description: 'Light, bubbly volcanic rock that floats on water' },
      { id: 'rhyolite',     name: 'Rhyolite',     type: 'igneous',      rarity: 'uncommon',  description: 'Light-colored fine-grained volcanic rock' },
      { id: 'andesite',     name: 'Andesite',     type: 'igneous',      rarity: 'uncommon',  description: 'Gray volcanic rock named after the Andes mountains' },
      { id: 'gabbro',       name: 'Gabbro',       type: 'igneous',      rarity: 'uncommon',  description: 'Dark coarse-grained rock from ocean crust' },
      { id: 'diorite',      name: 'Diorite',      type: 'igneous',      rarity: 'uncommon',  description: 'Salt-and-pepper speckled intrusive rock' },
      { id: 'tuff',         name: 'Tuff',         type: 'igneous',      rarity: 'common',    description: 'Rock formed from compacted volcanic ash' },
      { id: 'scoria',       name: 'Scoria',       type: 'igneous',      rarity: 'common',    description: 'Dark bubbly volcanic rock like a lava sponge' },
      { id: 'sandstone',    name: 'Sandstone',    type: 'sedimentary',  rarity: 'common',    description: 'Sand grains cemented together over millions of years' },
      { id: 'limestone',    name: 'Limestone',    type: 'sedimentary',  rarity: 'common',    description: 'Rock made from ancient shells and coral skeletons' },
      { id: 'shale',        name: 'Shale',        type: 'sedimentary',  rarity: 'common',    description: 'Thin-layered rock formed from compressed mud' },
      { id: 'conglomerate', name: 'Conglomerate', type: 'sedimentary',  rarity: 'common',    description: 'Rounded pebbles cemented together in a rock' },
      { id: 'chalk',        name: 'Chalk',        type: 'sedimentary',  rarity: 'common',    description: 'Soft white rock made from microscopic sea creatures' },
      { id: 'coal',         name: 'Coal',         type: 'sedimentary',  rarity: 'common',    description: 'Black rock formed from ancient compressed plants' },
      { id: 'mudstone',     name: 'Mudstone',     type: 'sedimentary',  rarity: 'common',    description: 'Fine-grained rock formed from ancient mud' },
      { id: 'siltstone',    name: 'Siltstone',    type: 'sedimentary',  rarity: 'common',    description: 'Rock made from very fine sediment particles' },
      { id: 'chert',        name: 'Chert',        type: 'sedimentary',  rarity: 'common',    description: 'Hard dense rock made from microscopic silica' },
      { id: 'breccia',      name: 'Breccia',      type: 'sedimentary',  rarity: 'uncommon',  description: 'Angular rock fragments cemented together' },
      { id: 'travertine',   name: 'Travertine',   type: 'sedimentary',  rarity: 'uncommon',  description: 'Layered limestone formed by hot springs' },
      { id: 'dolostone',    name: 'Dolostone',    type: 'sedimentary',  rarity: 'common',    description: 'Magnesium-rich rock similar to limestone' },
      { id: 'flint',        name: 'Flint',        type: 'sedimentary',  rarity: 'common',    description: 'Hard grey rock that makes sparks when struck' },
      { id: 'coquina',      name: 'Coquina',      type: 'sedimentary',  rarity: 'uncommon',  description: 'Rock made entirely of broken shell fragments' },
      { id: 'ironstone',    name: 'Ironstone',    type: 'sedimentary',  rarity: 'uncommon',  description: 'Reddish rock packed with iron minerals' },
      { id: 'marble',       name: 'Marble',       type: 'metamorphic',  rarity: 'uncommon',  description: 'Smooth elegant rock used in famous sculptures and buildings' },
      { id: 'slate',        name: 'Slate',        type: 'metamorphic',  rarity: 'common',    description: 'Fine-grained rock that splits into flat sheets' },
      { id: 'quartzite',    name: 'Quartzite',    type: 'metamorphic',  rarity: 'common',    description: 'Very hard sparkly rock transformed from sandstone' },
      { id: 'schist',       name: 'Schist',       type: 'metamorphic',  rarity: 'common',    description: 'Silvery foliated rock with visible mica flakes' },
      { id: 'gneiss',       name: 'Gneiss',       type: 'metamorphic',  rarity: 'common',    description: 'Banded rock with alternating dark and light layers' },
      { id: 'phyllite',     name: 'Phyllite',     type: 'metamorphic',  rarity: 'uncommon',  description: 'Silky-sheen rock between slate and schist' },
      { id: 'hornfels',     name: 'Hornfels',     type: 'metamorphic',  rarity: 'uncommon',  description: 'Hard fine-grained rock baked by contact with magma' },
      { id: 'serpentinite', name: 'Serpentinite', type: 'metamorphic',  rarity: 'uncommon',  description: 'Greenish rock with a snake-skin pattern' },
      { id: 'soapstone',    name: 'Soapstone',    type: 'metamorphic',  rarity: 'uncommon',  description: 'Soft soapy-feeling rock rich in talc' },
      { id: 'migmatite',    name: 'Migmatite',    type: 'metamorphic',  rarity: 'rare',      description: 'Rock that was partially melted and re-solidified deep underground' },
      { id: 'quartz',       name: 'Quartz',       type: 'mineral',      rarity: 'common',    description: 'Clear or white crystal — the most common mineral on Earth' },
      { id: 'feldspar',     name: 'Feldspar',     type: 'mineral',      rarity: 'common',    description: 'The most abundant mineral group in Earth\'s crust' },
      { id: 'mica',         name: 'Mica',         type: 'mineral',      rarity: 'common',    description: 'Shiny mineral that peels into thin flexible sheets' },
      { id: 'pyrite',       name: 'Pyrite',       type: 'mineral',      rarity: 'uncommon',  description: 'Shiny gold-colored mineral nicknamed "Fool\'s Gold"' },
      { id: 'calcite',      name: 'Calcite',      type: 'mineral',      rarity: 'common',    description: 'White mineral that makes up limestone and chalk' },
      { id: 'magnetite',    name: 'Magnetite',    type: 'mineral',      rarity: 'uncommon',  description: 'The only naturally magnetic mineral on Earth' },
      { id: 'gypsum',       name: 'Gypsum',       type: 'mineral',      rarity: 'common',    description: 'Soft white mineral used to make plaster and chalk' },
      { id: 'halite',       name: 'Halite',       type: 'mineral',      rarity: 'common',    description: 'Rock salt — the exact same mineral as table salt!' },
      { id: 'sulfur',       name: 'Sulfur',       type: 'mineral',      rarity: 'uncommon',  description: 'Bright yellow mineral found near volcanoes' },
      { id: 'talc',         name: 'Talc',         type: 'mineral',      rarity: 'common',    description: 'The softest mineral on Earth, used in baby powder' },
      { id: 'fluorite',     name: 'Fluorite',     type: 'mineral',      rarity: 'uncommon',  description: 'Colorful cubic crystals that glow under UV light' },
      { id: 'olivine',      name: 'Olivine',      type: 'mineral',      rarity: 'uncommon',  description: 'Olive-green mineral found in the Earth\'s mantle' },
      { id: 'hornblende',   name: 'Hornblende',   type: 'mineral',      rarity: 'uncommon',  description: 'Dark shiny mineral found in many igneous rocks' },
      { id: 'dolomite-m',   name: 'Dolomite',     type: 'mineral',      rarity: 'common',    description: 'Calcium magnesium carbonate mineral' },
      { id: 'peridotite',   name: 'Peridotite',   type: 'igneous',      rarity: 'uncommon',  description: 'Dense rock from deep in the Earth\'s mantle' },
    ]
  },
  {
    id: 'gemstones',
    name: 'Gemstones',
    icon: '💎',
    description: 'Precious and semi-precious gems from around the world',
    rocks: [
      { id: 'diamond',     name: 'Diamond',      type: 'gemstone', rarity: 'very rare', description: 'The hardest natural substance on Earth' },
      { id: 'ruby',        name: 'Ruby',         type: 'gemstone', rarity: 'rare',      description: 'Vivid red gemstone, a variety of corundum' },
      { id: 'emerald',     name: 'Emerald',      type: 'gemstone', rarity: 'very rare', description: 'Deep green gemstone, a variety of beryl' },
      { id: 'sapphire',    name: 'Sapphire',     type: 'gemstone', rarity: 'rare',      description: 'Brilliant blue gemstone, a variety of corundum' },
      { id: 'amethyst',    name: 'Amethyst',     type: 'gemstone', rarity: 'uncommon',  description: 'Purple variety of quartz with stunning crystals' },
      { id: 'topaz',       name: 'Topaz',        type: 'gemstone', rarity: 'rare',      description: 'Silicate mineral found in many beautiful colors' },
      { id: 'opal',        name: 'Opal',         type: 'gemstone', rarity: 'rare',      description: 'Gemstone that flashes rainbow colors' },
      { id: 'turquoise',   name: 'Turquoise',    type: 'gemstone', rarity: 'rare',      description: 'Blue-green gemstone used in ancient jewelry for thousands of years' },
      { id: 'jade',        name: 'Jade',         type: 'gemstone', rarity: 'rare',      description: 'Green gemstone sacred in many Asian cultures' },
      { id: 'garnet',      name: 'Garnet',       type: 'gemstone', rarity: 'rare',      description: 'Deep red gemstone found in metamorphic rocks' },
      { id: 'aquamarine',  name: 'Aquamarine',   type: 'gemstone', rarity: 'rare',      description: 'Blue-green beryl named for sea water' },
      { id: 'citrine',     name: 'Citrine',      type: 'gemstone', rarity: 'uncommon',  description: 'Yellow to orange variety of quartz' },
      { id: 'onyx',        name: 'Onyx',         type: 'gemstone', rarity: 'uncommon',  description: 'Black banded variety of chalcedony' },
      { id: 'pearl',       name: 'Pearl',        type: 'gemstone', rarity: 'rare',      description: 'Organic gem formed inside oysters and mollusks' },
      { id: 'moonstone',   name: 'Moonstone',    type: 'gemstone', rarity: 'rare',      description: 'Feldspar gem with a beautiful glowing blue sheen' },
      { id: 'obsidian-g',  name: 'Obsidian',     type: 'gemstone', rarity: 'common',    description: 'Volcanic glass used as a gemstone and ancient tool' },
      { id: 'malachite',   name: 'Malachite',    type: 'gemstone', rarity: 'rare',      description: 'Vivid green mineral with beautiful swirling patterns' },
      { id: 'lapis',       name: 'Lapis Lazuli', type: 'gemstone', rarity: 'rare',      description: 'Deep blue stone prized since ancient Egypt' },
      { id: 'rose-quartz', name: 'Rose Quartz',  type: 'gemstone', rarity: 'uncommon',  description: 'Pink variety of quartz, the love stone' },
      { id: 'tigers-eye',  name: "Tiger's Eye",  type: 'gemstone', rarity: 'uncommon',  description: 'Silky golden-brown stone with a shimmering optical effect' },
    ]
  },
  {
    id: 'minerals',
    name: 'Mineral Types',
    icon: '✨',
    description: 'Essential minerals that make up rocks',
    rocks: [
      { id: 'quartz-mn',      name: 'Quartz',      type: 'mineral', rarity: 'common',   description: 'Clear or white crystal, most common mineral on Earth' },
      { id: 'feldspar-mn',    name: 'Feldspar',    type: 'mineral', rarity: 'common',   description: 'Most abundant mineral group in Earth\'s crust' },
      { id: 'mica-mn',        name: 'Mica',        type: 'mineral', rarity: 'common',   description: 'Shiny mineral that splits into thin flexible sheets' },
      { id: 'calcite-mn',     name: 'Calcite',     type: 'mineral', rarity: 'common',   description: 'White mineral that makes up limestone and chalk' },
      { id: 'pyrite-mn',      name: 'Pyrite',      type: 'mineral', rarity: 'uncommon', description: 'Shiny Fool\'s Gold — iron sulfide mineral' },
      { id: 'magnetite-mn',   name: 'Magnetite',   type: 'mineral', rarity: 'uncommon', description: 'Naturally magnetic mineral — it sticks to magnets!' },
      { id: 'halite-mn',      name: 'Halite',      type: 'mineral', rarity: 'common',   description: 'Rock salt — you might even taste it!' },
      { id: 'gypsum-mn',      name: 'Gypsum',      type: 'mineral', rarity: 'common',   description: 'Soft white mineral used in plaster and drywall' },
      { id: 'sulfur-mn',      name: 'Sulfur',      type: 'mineral', rarity: 'uncommon', description: 'Bright yellow volcanic mineral with a distinctive smell' },
      { id: 'talc-mn',        name: 'Talc',        type: 'mineral', rarity: 'common',   description: 'Softest mineral on Earth — you can scratch it with a fingernail!' },
      { id: 'fluorite-mn',    name: 'Fluorite',    type: 'mineral', rarity: 'uncommon', description: 'Colorful cubic crystals that glow under UV light' },
      { id: 'biotite-mn',     name: 'Biotite',     type: 'mineral', rarity: 'common',   description: 'Dark brown to black mica mineral' },
      { id: 'orthoclase-mn',  name: 'Orthoclase',  type: 'mineral', rarity: 'common',   description: 'Pink feldspar mineral found in granite' },
      { id: 'plagioclase-mn', name: 'Plagioclase', type: 'mineral', rarity: 'common',   description: 'White to gray feldspar found in many rocks' },
      { id: 'olivine-mn',     name: 'Olivine',     type: 'mineral', rarity: 'uncommon', description: 'Olive-green mineral from Earth\'s mantle' },
    ]
  },
  {
    id: 'igneous',
    name: 'Igneous Rocks',
    icon: '🔥',
    description: 'Rocks formed from cooled magma and lava',
    rocks: [
      { id: 'granite-ig',   name: 'Granite',    type: 'igneous', rarity: 'common',   description: 'Coarse crystals from slow-cooling underground magma' },
      { id: 'basalt-ig',    name: 'Basalt',     type: 'igneous', rarity: 'common',   description: 'Dark volcanic rock, most common rock on Earth\'s surface' },
      { id: 'obsidian-ig',  name: 'Obsidian',   type: 'igneous', rarity: 'common',   description: 'Natural black volcanic glass with razor edges' },
      { id: 'pumice-ig',    name: 'Pumice',     type: 'igneous', rarity: 'common',   description: 'Frothy rock with so many bubbles it floats!' },
      { id: 'rhyolite-ig',  name: 'Rhyolite',  type: 'igneous', rarity: 'uncommon', description: 'Light-colored fine-grained volcanic rock' },
      { id: 'andesite-ig',  name: 'Andesite',  type: 'igneous', rarity: 'uncommon', description: 'Intermediate volcanic rock from stratovolcanoes' },
      { id: 'gabbro-ig',    name: 'Gabbro',    type: 'igneous', rarity: 'uncommon', description: 'Dark coarse-grained rock that forms ocean crust' },
      { id: 'diorite-ig',   name: 'Diorite',   type: 'igneous', rarity: 'uncommon', description: 'Speckled salt-and-pepper intrusive rock' },
      { id: 'tuff-ig',      name: 'Tuff',      type: 'igneous', rarity: 'common',   description: 'Volcanic ash compacted into rock over time' },
      { id: 'scoria-ig',    name: 'Scoria',    type: 'igneous', rarity: 'common',   description: 'Red or black bubbly volcanic rock from lava flows' },
      { id: 'perlite-ig',   name: 'Perlite',   type: 'igneous', rarity: 'uncommon', description: 'Glassy volcanic rock that pops and expands when heated' },
      { id: 'pegmatite-ig', name: 'Pegmatite', type: 'igneous', rarity: 'uncommon', description: 'Coarse granite with enormous crystals' },
      { id: 'syenite-ig',   name: 'Syenite',   type: 'igneous', rarity: 'uncommon', description: 'Like granite but without quartz crystals' },
      { id: 'dunite-ig',    name: 'Dunite',    type: 'igneous', rarity: 'rare',     description: 'Greenish rock made almost entirely of olivine from Earth\'s mantle' },
      { id: 'peridotite-ig',name: 'Peridotite',type: 'igneous', rarity: 'uncommon', description: 'Dense dark rock from deep inside the Earth' },
    ]
  },
  {
    id: 'sedimentary',
    name: 'Sedimentary Rocks',
    icon: '🏖️',
    description: 'Rocks built up from layers of sediment',
    rocks: [
      { id: 'sandstone-sd',   name: 'Sandstone',    type: 'sedimentary', rarity: 'common',   description: 'Sand grains glued together into rock by minerals' },
      { id: 'limestone-sd',   name: 'Limestone',    type: 'sedimentary', rarity: 'common',   description: 'Shells and coral from ancient seas turned to rock' },
      { id: 'shale-sd',       name: 'Shale',        type: 'sedimentary', rarity: 'common',   description: 'Compressed mud in thin layers — often contains fossils!' },
      { id: 'conglom-sd',     name: 'Conglomerate', type: 'sedimentary', rarity: 'common',   description: 'Big pebbles and boulders cemented in a fine matrix' },
      { id: 'chalk-sd',       name: 'Chalk',        type: 'sedimentary', rarity: 'common',   description: 'Soft white rock made from billions of tiny sea creatures' },
      { id: 'coal-sd',        name: 'Coal',         type: 'sedimentary', rarity: 'common',   description: 'Black rock from forests that lived 300 million years ago' },
      { id: 'mudstone-sd',    name: 'Mudstone',     type: 'sedimentary', rarity: 'common',   description: 'Ancient mud turned to stone over millions of years' },
      { id: 'siltstone-sd',   name: 'Siltstone',    type: 'sedimentary', rarity: 'common',   description: 'Very fine sediment particles cemented into rock' },
      { id: 'chert-sd',       name: 'Chert',        type: 'sedimentary', rarity: 'common',   description: 'Hard rock made from microscopic silica organisms' },
      { id: 'breccia-sd',     name: 'Breccia',      type: 'sedimentary', rarity: 'uncommon', description: 'Angular broken rock fragments cemented together' },
      { id: 'travertine-sd',  name: 'Travertine',   type: 'sedimentary', rarity: 'uncommon', description: 'Beautiful layered limestone deposited by hot springs' },
      { id: 'dolostone-sd',   name: 'Dolostone',    type: 'sedimentary', rarity: 'common',   description: 'Magnesium-rich limestone with a slightly different chemistry' },
      { id: 'flint-sd',       name: 'Flint',        type: 'sedimentary', rarity: 'common',   description: 'Hard grey rock — early humans used it to make tools and fire!' },
      { id: 'ironstone-sd',   name: 'Ironstone',    type: 'sedimentary', rarity: 'uncommon', description: 'Iron-rich red-brown rock formed in shallow ancient seas' },
      { id: 'coquina-sd',     name: 'Coquina',      type: 'sedimentary', rarity: 'uncommon', description: 'Rock made entirely of glued-together shell pieces' },
    ]
  },
  {
    id: 'metamorphic',
    name: 'Metamorphic Rocks',
    icon: '💫',
    description: 'Rocks transformed by heat and pressure',
    rocks: [
      { id: 'marble-mt',       name: 'Marble',       type: 'metamorphic', rarity: 'uncommon', description: 'Transformed limestone — used in the most famous statues in history!' },
      { id: 'slate-mt',        name: 'Slate',        type: 'metamorphic', rarity: 'common',   description: 'Splits into flat sheets, used for roofing and chalkboards' },
      { id: 'quartzite-mt',    name: 'Quartzite',    type: 'metamorphic', rarity: 'common',   description: 'Super-hard sandstone baked by incredible heat and pressure' },
      { id: 'schist-mt',       name: 'Schist',       type: 'metamorphic', rarity: 'common',   description: 'Silvery foliated rock with sparkling mica flakes' },
      { id: 'gneiss-mt',       name: 'Gneiss',       type: 'metamorphic', rarity: 'common',   description: 'Striped banded rock with alternating dark and light layers' },
      { id: 'phyllite-mt',     name: 'Phyllite',     type: 'metamorphic', rarity: 'uncommon', description: 'Silky-looking rock halfway between slate and schist' },
      { id: 'hornfels-mt',     name: 'Hornfels',     type: 'metamorphic', rarity: 'uncommon', description: 'Very hard fine-grained rock baked by nearby magma' },
      { id: 'serpentin-mt',    name: 'Serpentinite', type: 'metamorphic', rarity: 'uncommon', description: 'Waxy green rock named for its snake-skin pattern' },
      { id: 'soapstone-mt',    name: 'Soapstone',    type: 'metamorphic', rarity: 'uncommon', description: 'Soft soapy-feeling rock used for carvings for centuries' },
      { id: 'migmatite-mt',    name: 'Migmatite',    type: 'metamorphic', rarity: 'rare',     description: 'Rock that partially melted deep underground then solidified' },
      { id: 'eclogite-mt',     name: 'Eclogite',     type: 'metamorphic', rarity: 'rare',     description: 'Rare high-pressure rock formed deep inside the Earth' },
      { id: 'blueschist-mt',   name: 'Blueschist',   type: 'metamorphic', rarity: 'rare',     description: 'Blue-tinged rock formed under extreme cold pressure deep in the Earth' },
      { id: 'greenschist-mt',  name: 'Greenschist',  type: 'metamorphic', rarity: 'uncommon', description: 'Green-colored rock formed at moderate temperature and pressure' },
      { id: 'anthracite-mt',   name: 'Anthracite',   type: 'metamorphic', rarity: 'uncommon', description: 'The highest grade of coal — shiny jet-black and very hard' },
      { id: 'mylonite-mt',     name: 'Mylonite',     type: 'metamorphic', rarity: 'rare',     description: 'Rock ground to powder and recrystallized along fault lines' },
    ]
  },
];
